language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t tenzinkunkhen/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tenzinkunkhen/docker-react-app npm run test